peptides = [
    "BPC-157",
    "TB-500",
    "KPV",
    "Selank",
    "Semax",
    "Melanotan II",
    "CJC-1295",
    "Ipamorelin",
    "GHRP-6",
    "Thymosin Alpha-1",
    "Thymosin Beta-4",
    "Epithalon",
    "Hexarelin",
    "PT-141",
    "DSIP",
    "Follistatin",
    "GHK",
    "IGF-1 LR3",
    "AOD9604",
    "MOTS-c",
    "Violin",
    "Bremelanotide",
    "LL-37",
    "Tesamorelin",
    "Thymalin",
    "Vasoactive Intestinal Peptide (VIP)",
    "Cerebrolysin",
    "Pinealon",
    "Selank",
    "Thymogen",
    "Amlexanox",
    "Alistatin",
    "Argireline",
    "Collagen Peptide",
    "Palmitoyl Pentapeptide-4",
    "Palmitoyl Tripeptide-1",
    "Snap-8",
    "Sermorelin",
    "Liraglutide",
    "Tirzepatide",
    "Exenatide"
]

nootropics = [
    "Piracetam",
    "Aniracetam",
    "Oxiracetam",
    "Pramiracetam",
    "Noopept",
    "Phenylpiracetam",
    "Modafinil",
    "Adrafinil",
    "Armodafinil",
    "Phenibut",
    "L-Theanine",
    "Caffeine",
    "Rhodiola Rosea",
    "Ashwagandha",
    "Bacopa Monnieri",
    "Ginkgo Biloba",
    "Huperzine A",
    "Alpha-GPC",
    "Citicoline",
    "Choline Bitartrate",
    "Lion's Mane Mushroom",
    "Cordyceps",
    "Mucuna Pruriens",
    "Phenylalanine",
    "Tyrosine",
    "Acetyl-L-Carnitine",
    "N-Acetyl L-Tyrosine",
    "5-HTP",
    "SAM-e",
    "PQQ (Pyrroloquinoline Quinone)",
    "CoQ10",
    "Creatine",
    "Omega-3 Fatty Acids",
    "Curcumin",
    "Resveratrol",
    "Pterostilbene",
    "Sulbutiamine",
    "Uridine Monophosphate",
    "Forskolin",
    "Artichoke Extract"
]

genres = [
    "Longevity",
    "Hair Health",
    "Bone Health",
    "Cognition",
    "Memory",
    "Focus",
    "Mood Enhancement",
    "Stress Reduction",
    "Sleep Improvement",
    "Energy Boosting",
    "Immune Support",
    "Anti-Inflammatory",
    "Weight Management",
    "Muscle Growth",
    "Joint Health",
    "Cardiovascular Health",
    "Digestive Health",
    "Liver Support",
    "Detoxification",
    "Hormonal Balance",
    "Skin Health",
    "Eye Health",
    "Antioxidant Support",
    "Blood Sugar Regulation"
]